name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out into $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      - uses: wenkokke/setup-agda@v2
      - run: agda HoTT/Univalence.agda
        working-directory: src
      - run: agda FP/zio-prelude/Zio.agda
        working-directory: src

      - run: |
          agda HoTT/Univalence.agda
          agda FP/zio-prelude/Zio.agda
        working-directory: src
