name: CI

# when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # type of runner
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Runs a single command
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
